sudo: false

language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
branches:
  only:
    - staging
    - trying
    - master

script:
  cargo test --all
