[package]
name = "panopaea-python"
version = "0.1.0"
authors = ["msiglreith <msiglreith@users.noreply.github.com>"]
workspace = ".."

[lib]
name = "panopaea_python"

[dependencies]
cpython = "0.1.0"
numpy = "0.2.1"
